name: Trigger Base Branch Change
on:
  pull_request:
    types:
        - edited


jobs:
  trigger_integration:
        name: Check preconditions and cancel previous jobs
        if: ${{ github.event.changes.base && github.event.pull_request.base.ref == 'main' }}
        runs-on: ubuntu-latest

        steps:
            - name: trigger integration
              run: |
                echo Muneeb
                BRANCH_REF="${{ github.head_ref }}"
                curl -X POST \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -d '{"labels":["trigger-second-workflow"]}'