name: Trigger Workflow on Base Branch Change

on:
  pull_request:
    types:
      - edited  # Triggers on changes to the PR, including base branch changes

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.changes.base && github.event.pull_request.base.ref == 'main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch latest changes and rebase
        run: |
          git fetch origin
          git rebase origin/${{ github.head_ref }}

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "Trigger workflows due to base branch change"

      - name: Push commit
        run: |
          git push origin HEAD:${{ github.head_ref }} --force-with-lease

      - name: Post a comment on the PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "An empty commit was added to trigger workflows due to the base branch change."
            })
